//**********************************************************
//This file will contain the github action that will 
//install our project, build it and then deploy it to our 
//lambda function
//**********************************************************

name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
     - name: npm install
        env:
          CI: true
        run: |
          npm ci
  